# Generated by Django 3.0.8 on 2020-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=80)),
                ('phone', models.CharField(default='', max_length=80)),
                ('feedback', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
