# Generated by Django 3.1.4 on 2021-01-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_userbase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='emaild',
            new_name='emailid',
        ),
    ]
