# Generated by Django 3.1.4 on 2021-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210114_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='emailid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
