# Generated by Django 3.1.4 on 2021-01-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210114_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userbase',
        ),
    ]
